[package]
name = "term-kit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
copypasta = "0.10.1"
crossterm = "0.28.1"
directories = "6.0.0"
ratatui = "0.29.0"
serde = { version = "1.0.218", features = ["derive"] }
textwrap = "0.16.1"
wl-clipboard-rs = "0.9.1"
